In [7]:
!pip install truth-table-generator


You should consider upgrading via the 'c:\users\tanee\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [3]:
import ttg
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from sklearn.datasets import load_iris

import numpy as np
import matplotlib.pyplot as plt

In [35]:
datas = [{"group":"group0","AGE":"ANY",'disease':"ANY","hasCough":"ANY","hasFever":"ANY","tired":"ANY","hasCloser":"False","Travel":"False"},{"group":"group1","AGE":"ANY",'disease':"ANY","hasCough":"ANY","hasFever":"False","tired":"ANY","hasCloser":"True","Travel":"True"},{"group":"group1","AGE":"ANY",'disease':"ANY","hasCough":"False","hasFever":"True","tired":"False","hasCloser":"True","Travel":"True"}]

In [574]:
    datas = [{"group": "group0", "AGE": "False", 'disease': "ANY", "cough": "ANY", "Fever": "ANY", "tired": "ANY", "close": "False", "Travel": "False"}, {"group": "group1", "AGE": "ANY", 'disease': "ANY", "cough": "ANY", "Fever": "False", "tired": "ANY", "close": "True", "Travel": "True"}, {
            "group": "group1p2", "AGE": "False", 'disease': "ANY", "cough": "False", "Fever": "True", "tired": "False", "close": "True", "Travel": "True"}, {
            "group": "group2", "AGE": 5, 'disease': "False", "Fever": "True", "close": "True", "Travel": "True", "Relation": [["cough", "tired"]]}, {
            "group": "group3", "AGE": 4, 'disease': "False", "Fever": "True", "close": "True", "Travel": "True", "Relation": [["cough", "tired"]]
    },{
        "group": "group3", "AGE": "False", 'disease': "True", "Fever": "True", "close": "True", "Travel": "True", "Relation": [["cough", "tired"]]
    },
    {
        "group": "group4", "AGE": "False", 'disease': "ANY", "Fever": "True", "close": "ANY", "Travel": "True","cough":"True","tired":"True"
    }
    ]

In [575]:
def checkOr(newDF2):
    arr = []
    for index, row in newDF2.iterrows():
        arr.append(row['close'] or  row['Travel'] )
    newDF2['hasCloserOrTravel']  = arr

#     newDF2['hasCloserOrTravel'] =  newDF2['hasCloser'] or newDF2['Travel']
    

In [576]:
import numpy as np
newDF = pd.DataFrame()
newDF2 = pd.DataFrame()
flag = False
cols2 = []
# mainCols = list(datas[0].keys())
# print(mainCols)
for data in datas:
    df = pd.DataFrame()
    list2 = []
    Any = []
    notYet = []
    relation = []
    for i in data:
        if data[i] == 'ANY':
            Any.append(i)
        elif i != 'ANY' and i !=  "Relation" :
            notYet.append(i)
        elif i == "Relation":
            relation.append(data[i])

    if len(Any) > 0 :
        truthTable = ttg.Truths(Any)
        df = truthTable.as_pandas()
    if flag == False:

        cols = df.columns

        cols = list(cols)
        cols = cols+notYet
#         print(cols)
        flag = True
        for arr in notYet:
            df[arr] =data[arr]
            head = list(df.columns)
    else:
        cols2 = df.columns
        cols2 = list(cols2)
        for i in cols:
            if i not in cols2:

                list2.append(i)

#         print(notYet)
#         print(data)
#         print(list2)
        if len(relation) >0:
            for i in list2:
                if i in relation[0][0]:
                    list2.remove(i)
        for arr in list2:
            if df.empty:
                d = data[arr]
                print("D = ", d)
                df = df.append({arr: d}, ignore_index=True)
#             print(df)
#             print("_____")
            else:
                print(data)
                data_series = pd.Series([data[arr]])
                df[arr] = data[arr] #2
        head = list(df.columns)

        print(df)
    for i in notYet:
        colum = df.columns
    df = df.reindex(sorted(df.columns), axis=1)
    if len(relation) > 0:
        for i in range(len(relation)):
            for idxJ, j in enumerate(relation[i]):

                head = head +j

                listDF = df.to_numpy()
                newList = []
                for idxK, k in enumerate(listDF):
#                     print(listDF)
                    for idx, val in enumerate(j):
                        for idxM, m in enumerate(j):
                            if idx == idxM:
                                newList.append("True")
                            else :
                                newList.append("False")
#                         print(k)
                        newList = np.append(k,newList)
                        if newDF2.empty:
                            newDF2 = pd.DataFrame([newList], 
                         columns=[head])
                        else :
                            newDF2.loc[len(newDF2)]=newList
                        newList = []
    else:

        if newDF2.empty:
            newDF2 = df
        else:
            newDF2 = newDF2.append(df,ignore_index=True)
        
checkOr(newDF2)






    


{'group': 'group1', 'AGE': 'ANY', 'disease': 'ANY', 'cough': 'ANY', 'Fever': 'False', 'tired': 'ANY', 'close': 'True', 'Travel': 'True'}
{'group': 'group1', 'AGE': 'ANY', 'disease': 'ANY', 'cough': 'ANY', 'Fever': 'False', 'tired': 'ANY', 'close': 'True', 'Travel': 'True'}
{'group': 'group1', 'AGE': 'ANY', 'disease': 'ANY', 'cough': 'ANY', 'Fever': 'False', 'tired': 'ANY', 'close': 'True', 'Travel': 'True'}
{'group': 'group1', 'AGE': 'ANY', 'disease': 'ANY', 'cough': 'ANY', 'Fever': 'False', 'tired': 'ANY', 'close': 'True', 'Travel': 'True'}
   AGE disease cough tired  Fever   group close Travel
1    1       1     1     1  False  group1  True   True
2    1       1     1     0  False  group1  True   True
3    1       1     0     1  False  group1  True   True
4    1       1     0     0  False  group1  True   True
5    1       0     1     1  False  group1  True   True
6    1       0     1     0  False  group1  True   True
7    1       0     0     1  False  group1  True   True
8    1      

In [577]:
newDF2 = newDF2.reindex(sorted(newDF2.columns), axis=1)
newDF2


AGE  Fever Travel  close  cough disease     group hasCloserOrTravel  \
0   False      1  False  False      1       1    group0             False   
1   False      1  False  False      1       1    group0             False   
2   False      0  False  False      1       1    group0             False   
3   False      0  False  False      1       1    group0             False   
4   False      1  False  False      0       1    group0             False   
5   False      1  False  False      0       1    group0             False   
6   False      0  False  False      0       1    group0             False   
7   False      0  False  False      0       1    group0             False   
8   False      1  False  False      1       0    group0             False   
9   False      1  False  False      1       0    group0             False   
10  False      0  False  False      1       0    group0             False   
11  False      0  False  False      1       0    group0             False   
12  False      1  False  False      0       0    group0             False   
13  False      1  False  False      0       0    group0             False   
14  False      0  False  False      0       0    group0             False   
15  False      0  False  False      0       0    group0             False   
16      1  False   True   True      1       1    group1              True   
17      1  False   True   True      1       1    group1              True   
18      1  False   True   True      0       1    group1              True   
19      1  False   True   True      0       1    group1              True   
20      1  False   True   True      1       0    group1              True   
21      1  False   True   True      1       0    group1              True   
22      1  False   True   True      0       0    group1              True   
23      1  False   True   True      0       0    group1              True   
24      0  False   True   True      1       1    group1              True   
25      0  False   True   True      1       1    group1              True   
26      0  False   True   True      0       1    group1              True   
27      0  False   True   True      0       1    group1              True   
28      0  False   True   True      1       0    group1              True   
29      0  False   True   True      1       0    group1              True   
30      0  False   True   True      0       0    group1              True   
31      0  False   True   True      0       0    group1              True   
32  False   True   True   True  False       1  group1p2              True   
33  False   True   True   True  False       0  group1p2              True   
34      5   True   True   True  False  group2      True              True   
35      5   True   True   True  False  group2     False              True   
36      4   True   True   True  False  group3      True              True   
37      4   True   True   True  False  group3     False              True   
38  False   True   True   True   True  group3      True              True   
39  False   True   True   True   True  group3     False              True   
40  False   True   True      1   True       1    group4                 1   
41  False   True   True      0   True       1    group4              True   
42  False   True   True      1   True       0    group4                 1   
43  False   True   True      0   True       0    group4              True   

    tired  
0       1  
1       0  
2       1  
3       0  
4       1  
5       0  
6       1  
7       0  
8       1  
9       0  
10      1  
11      0  
12      1  
13      0  
14      1  
15      0  
16      1  
17      0  
18      1  
19      0  
20      1  
21      0  
22      1  
23      0  
24      1  
25      0  
26      1  
27      0  
28      1  
29      0  
30      1  
31      0  
32  False  
33  False  
34  False  
35   True  
36  False  
37   True  
38  False  
39   True  
40   True  
41   True  
42   True  
43   True

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.transform(["tokyo", "tokyo", "paris"])

In [493]:
newDF2 = newDF2.replace("True", 1)
newDF2 = newDF2.replace("False", 0)
# newDF2newDF2 = newDF.replace("group0", 0)
newDF2 = newDF2.replace("group0", 0)
newDF2 = newDF2.replace("group1", 1)
newDF2 = newDF2.replace("group1p2", 1)
newDF2 = newDF2.replace("group2", 2)
newDF2 = newDF2.replace("group3", 3)
newDF2 = newDF2.replace("group4", 4)

In [494]:
newDF2.head(5)

Travel  age  disease  group  hasCloser  hasCough  hasFever  tired  \
0       0    0        1      0          0         1         1      1   
1       0    0        1      0          0         1         1      0   
2       0    0        1      0          0         1         0      1   
3       0    0        1      0          0         1         0      0   
4       0    0        1      0          0         0         1      1   

   hasCloserOrTravel  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0

In [4]:
import csv
with open('dataset4.csv', newline='',encoding='utf-8') as csvfile:
    reader = csv.DictReader(csvfile)
    dict1 = {}
    newList = []
    for row in reader:
        dict1['hasCloser'] = row['isCloseToCovid19Patient']
        dict1['disease'] = row['haveUnderlyingDisease']
        dict1['hasFever'] = row['haveFever']
        dict1['tired'] = row['haveTired']
        dict1['Travel'] = row['isTravelToCovid19Country']
        dict1['group'] = row['outcome']
        dict1['hasCough'] = row['haveCough']
        dict1['age'] = row['ageGroup']
        newList.append(dict1)
        dict1 = {}



In [6]:
df = pd.DataFrame.from_dict(newList)
df

hasCloser disease hasFever  tired Travel     group hasCough  \
0        FALSE   FALSE     TRUE   TRUE   TRUE  GROUP1p1     TRUE   
1        FALSE   FALSE     TRUE   TRUE   TRUE  GROUP1p1     TRUE   
2        FALSE   FALSE     TRUE   TRUE   TRUE  GROUP1p1     TRUE   
3         TRUE   FALSE     TRUE   TRUE   TRUE  GROUP1p1     TRUE   
4         TRUE   FALSE     TRUE   TRUE   TRUE  GROUP1p1     TRUE   
...        ...     ...      ...    ...    ...       ...      ...   
2705     FALSE   FALSE    FALSE  FALSE  FALSE    GROUP4    FALSE   
2706     FALSE   FALSE    FALSE  FALSE  FALSE    GROUP4    FALSE   
2707     FALSE   FALSE    FALSE   TRUE  FALSE    GROUP4    FALSE   
2708     FALSE   FALSE    FALSE  FALSE  FALSE    GROUP4    FALSE   
2709     FALSE   FALSE    FALSE  FALSE  FALSE    GROUP4    FALSE   

                    age  
0             OLD_ADULT  
1     MIDDLE_AGED_ADULT  
2           YOUNG_ADULT  
3           YOUNG_ADULT  
4           YOUNG_ADULT  
...                 ...  
2705             JUNIOR  
2706  MIDDLE_AGED_ADULT  
2707  MIDDLE_AGED_ADULT  
2708          OLD_ADULT  
2709             SENIOR  

[2710 rows x 8 columns]

In [497]:
df = df.replace("TRUE", 1)
df = df.replace("FALSE", 0)
df = df.replace("SENIOR", 5)
df = df.replace("OLD_ADULT", 4)
df = df.replace("MIDDLE_AGED_ADULT", 3)
df = df.replace("YOUNG_ADULT", 2)
df = df.replace("JUNIOR", 1)
df = df.replace("ELDER", 6)
df = df.replace("GROUP1p1", 4)
df = df.replace("GROUP1p2", 3)
df = df.replace("GROUP2", 2)
df = df.replace("GROUP3", 1)
df = df.replace("GROUP4", 0)

In [15]:
df0 = df[df.group == "GROUP2"]

In [16]:
df0

hasCloser disease hasFever  tired Travel   group hasCough  \
21      TRUE   FALSE     TRUE   TRUE   TRUE  GROUP2    FALSE   
22      TRUE   FALSE     TRUE   TRUE  FALSE  GROUP2    FALSE   
23     FALSE   FALSE     TRUE  FALSE   TRUE  GROUP2     TRUE   
24      TRUE   FALSE     TRUE   TRUE   TRUE  GROUP2    FALSE   
25      TRUE   FALSE     TRUE   TRUE   TRUE  GROUP2    FALSE   
26     FALSE   FALSE     TRUE  FALSE   TRUE  GROUP2     TRUE   
27      TRUE   FALSE     TRUE  FALSE  FALSE  GROUP2     TRUE   
28      TRUE   FALSE     TRUE   TRUE   TRUE  GROUP2    FALSE   
29     FALSE   FALSE     TRUE  FALSE   TRUE  GROUP2     TRUE   
30     FALSE   FALSE     TRUE  FALSE   TRUE  GROUP2     TRUE   

                  age  
21  MIDDLE_AGED_ADULT  
22        YOUNG_ADULT  
23             JUNIOR  
24        YOUNG_ADULT  
25        YOUNG_ADULT  
26  MIDDLE_AGED_ADULT  
27  MIDDLE_AGED_ADULT  
28             JUNIOR  
29        YOUNG_ADULT  
30             JUNIOR

In [498]:
df[df['hasFever'] == ''].index

Int64Index([1521, 1522, 1523, 2400, 2401, 2402], dtype='int64')

In [499]:

df = df.drop([2403,1522, 1523, 2401, 2402,1524,1521,2400]).reset_index()

In [500]:
df.astype('int32').dtypes

index        int32
hasCloser    int32
disease      int32
hasFever     int32
tired        int32
Travel       int32
group        int32
hasCough     int32
age          int32
dtype: object

In [501]:
df = df.drop(['index'], axis='columns')

In [502]:
df

hasCloser disease hasFever tired Travel group hasCough age
0            0       0        1     1      1     4        1   4
1            0       0        1     1      1     4        1   3
2            0       0        1     1      1     4        1   2
3            1       0        1     1      1     4        1   2
4            1       0        1     1      1     4        1   2
...        ...     ...      ...   ...    ...   ...      ...  ..
2697         0       0        0     0      0     0        0   1
2698         0       0        0     0      0     0        0   3
2699         0       0        0     1      0     0        0   3
2700         0       0        0     0      0     0        0   4
2701         0       0        0     0      0     0        0   5

[2702 rows x 8 columns]

In [503]:

arr = []
for index, row in df.iterrows():
    arr.append(row['hasCloser'] or  row['Travel'] )
df['hasCloserOrTravel']  = arr

#     newDF2['hasCloserOrTravel'] =  newDF2['hasCloser'] or newDF2['Travel']
    

In [504]:
df.head(5)

hasCloser disease hasFever tired Travel group hasCough age  \
0         0       0        1     1      1     4        1   4   
1         0       0        1     1      1     4        1   3   
2         0       0        1     1      1     4        1   2   
3         1       0        1     1      1     4        1   2   
4         1       0        1     1      1     4        1   2   

   hasCloserOrTravel  
0                  1  
1                  1  
2                  1  
3                  1  
4                  1

In [505]:
df = df.reindex(sorted(df.columns), axis=1)
newDF2 = newDF2.reindex(sorted(newDF2.columns), axis=1)

In [519]:
newDF2

Travel  age  disease  group  hasCloser  hasCloserOrTravel  hasCough  \
0        0    0        1      0          0                  0         1   
1        0    0        1      0          0                  0         1   
2        0    0        1      0          0                  0         1   
3        0    0        1      0          0                  0         1   
4        0    0        1      0          0                  0         0   
5        0    0        1      0          0                  0         0   
6        0    0        1      0          0                  0         0   
7        0    0        1      0          0                  0         0   
8        0    0        0      0          0                  0         1   
9        0    0        0      0          0                  0         1   
10       0    0        0      0          0                  0         1   
11       0    0        0      0          0                  0         1   
12       0    0        0      0          0                  0         0   
13       0    0        0      0          0                  0         0   
14       0    0        0      0          0                  0         0   
15       0    0        0      0          0                  0         0   
16       1    1        1      1          1                  1         1   
17       1    1        1      1          1                  1         1   
18       1    1        1      1          1                  1         0   
19       1    1        1      1          1                  1         0   
20       1    1        0      1          1                  1         1   
21       1    1        0      1          1                  1         1   
22       1    1        0      1          1                  1         0   
23       1    1        0      1          1                  1         0   
24       1    0        1      1          1                  1         1   
25       1    0        1      1          1                  1         1   
26       1    0        1      1          1                  1         0   
27       1    0        1      1          1                  1         0   
28       1    0        0      1          1                  1         1   
29       1    0        0      1          1                  1         1   
30       1    0        0      1          1                  1         0   
31       1    0        0      1          1                  1         0   
32       1    0        1      1          1                  1         0   
33       1    0        0      1          1                  1         0   
34       1    5        0      2          1                  1         1   
35       1    5        0      2          1                  1         1   
36       1    4        0      3          1                  1         1   
37       1    4        0      3          1                  1         1   
38       1    0        1      3          1                  1         1   
39       1    0        1      3          1                  1         1   
40       1    0        1      4          1                  1         1   
41       1    0        1      4          0                  1         1   
42       1    0        0      4          1                  1         1   
43       1    0        0      4          0                  1         1   

    hasFever  tired  
0          1      1  
1          1      0  
2          0      1  
3          0      0  
4          1      1  
5          1      0  
6          0      1  
7          0      0  
8          1      1  
9          1      0  
10         0      1  
11         0      0  
12         1      1  
13         1      0  
14         0      1  
15         0      0  
16         0      1  
17         0      0  
18         0      1  
19         0      0  
20         0      1  
21         0      0  
22         0      1  
23         0      0  
24         0      1  
25         0      0  
26         0      1  
27         0

In [506]:
#SVM

In [507]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

from matplotlib import pyplot as plt
%matplotlib inline

In [508]:
df = df.reindex(sorted(df.columns), axis=1)
newDF2 = newDF2.reindex(sorted(newDF2.columns), axis=1)

In [509]:
y_train = newDF2.group
X_train = newDF2.drop(['group'], axis='columns')

In [510]:
X_test  = df.drop(['group'], axis='columns')
y_test = df.group

In [511]:
X_test['age'] = pd.Series(X_test['AGE'], dtype="int64")
X_test['Travel'] = pd.Series(X_test['Travel'], dtype="int64")
X_test['disease'] = pd.Series(X_test['disease'], dtype="int64")
X_test['hasCloser'] = pd.Series(X_test['hasCloser'], dtype="int64")
X_test['hasCough'] = pd.Series(X_test['hasCough'], dtype="int64")
X_test['hasFever'] = pd.Series(X_test['hasFever'], dtype="int64")
X_test['tired'] = pd.Series(X_test['tired'], dtype="int64")


KeyError: 'AGE'

In [512]:
y_test= pd.Series(y_test, dtype="int64")

In [513]:
model = SVC(kernel='linear')
model.fit(X_train, y_train)
print("accuracy DT train: {:.3f}".format(model.score(X_train, y_train)))

accuracy DT train: 0.955


In [514]:
predictions = model.predict(X_test)
print(predictions)

[2 2 4 ... 0 0 2]


In [515]:
X_test

Travel age disease hasCloser  hasCloserOrTravel hasCough hasFever tired
0         1   4       0         0                  1        1        1     1
1         1   3       0         0                  1        1        1     1
2         1   2       0         0                  1        1        1     1
3         1   2       0         1                  1        1        1     1
4         1   2       0         1                  1        1        1     1
...     ...  ..     ...       ...                ...      ...      ...   ...
2697      0   1       0         0                  0        0        0     0
2698      0   3       0         0                  0        0        0     0
2699      0   3       0         0                  0        0        0     1
2700      0   4       0         0                  0        0        0     0
2701      0   5       0         0                  0        0        0     0

[2702 rows x 8 columns]

In [516]:
y_test

0       4
1       4
2       4
3       4
4       4
       ..
2697    0
2698    0
2699    0
2700    0
2701    0
Name: group, Length: 2702, dtype: int64

In [517]:
percentage = model.score(X_test, y_test)

In [518]:
from sklearn.metrics import confusion_matrix
res = confusion_matrix(y_test, predictions)
print("Confusion Matrix")
print(res)
print(f"Test Set: {len(X_test)}")
print(f"Accuracy = {percentage*100} %")

Confusion Matrix
[[1744    0  300    0    0]
 [   0  259   45  323    0]
 [   0    4    1    3    2]
 [   0    0    2    4    0]
 [   0    0    5    0   10]]
Test Set: 2702
Accuracy = 74.68541820873426 %


In [432]:
X_train

Travel  age  disease  hasCloser  hasCloserOrTravel  hasCough  hasFever  \
0        0  1.0        1          0                  0         1         1   
1        0  1.0        1          0                  0         1         1   
2        0  1.0        1          0                  0         1         0   
3        0  1.0        1          0                  0         1         0   
4        0  1.0        1          0                  0         0         1   
..     ...  ...      ...        ...                ...       ...       ...   
63       1  1.0        0          0                  1         1         1   
64       1  0.0        1          1                  1         1         1   
65       1  0.0        1          0                  1         1         1   
66       1  0.0        0          1                  1         1         1   
67       1  0.0        0          0                  1         1         1   

    tired  
0       1  
1       0  
2       1  
3       0  
4       1  
..    ...  
63      1  
64      1  
65      1  
66      1  
67      1  

[68 rows x 8 columns]

In [433]:
0-10 2
11-20 3
21-30 4
40-50 5

SyntaxError: invalid syntax (Temp/ipykernel_8932/1296420641.py, line 1)